config/routes.rb
Rails.application.routes.draw do
  resources :teams, only: [:index]
  resources :contacts, only: [:index]
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]
  resources :gossips do
    resources :comments
  end
  root 'gossips#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    validates :email, presence: true
    belongs_to :city, optional: true
    has_many :gossips
    has_many :comments
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"

    def remember(remember_token)
        remember_digest = BCrypt::Password.create(remember_token)
        self.update(remember_digest: remember_digest)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(email: params[:email], password: params[:password], city_id: rand(1..10))

    if @user.save
      flash[:success] = "Session créée, bienvenu.e dans la communauté des potins !"
      #création d'une session
      log_in(user)
      #création d'un cookie
      remember(user)
      redirect_to root_path
    else
      puts @user
      puts "user not saved due to errors"
      puts @user.errors.full_messages
      render new_user_path
    end 
  end

  def update
  end

  def show
    @user = User.all.find(params[:id].to_i)
  end

  def destroy
  end

  def edit
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<% if @user.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <p>La session n'a pas pu être créée pour la (ou les) raison(s) suivante(s) :</p>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

<div class="container">
    <div class=text-center>
    <h1>Créer un compte :</h1>

    <%= form_tag users_path, method: "post" do %>
    <div class="form-group">
        <%= label_tag 'email' %><br/>
        <%= text_field_tag 'email' %>
        <br /> <br />
    </div>
    <div class="form-group">
        <%= label_tag 'mot de passe' %><br/>
        <%= password_field_tag 'password' %>
        <br /> <br />
    </div>
        <%= submit_tag "Valider", class: "btn btn-info" %>
    <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="text-center">
        <h1><%= @user.first_name %> <%= @user.last_name %></h1>
        <p>Email : <%= @user.email%><br/>
        Age : <%= @user.age%><br/>
        Ville : <% if @user.city != nil %>
                    de <%= link_to @user.city.name, city_path(@user.city.id), class:"text-info" %><br/>
                <% end %></p>
        Présentation : <%= @user.description%></p>
    </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>