config/routes.rb
Rails.application.routes.draw do
  resources :teams, only: [:index]
  resources :contacts, only: [:index]
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]
  resources :gossips do
    resources :comments
  end
  root 'gossips#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    validates :title, presence: true, length: { minimum: 3, maximum: 14}
    validates :content, presence: true
    belongs_to :user
    has_many :gossip_tags
    has_many :tags, through: :gossip_tags
    has_many :comments

    def self.count 
        return self.all.size 
    end 

    def self.get_author_first_names
        author_array = []
        self.all.each do |g|
            author_array << g.user.first_name
        end 
        return author_array
    end 

    def self.get_titles
        title_array = []
        self.all.each do |g|
            title_array << g.title 
        end
        return title_array
    end 

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:new, :edit, :destroy]
  before_action :is_author?, only: [:edit, :destroy]

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(title: params["gossip_title"], content: params["gossip_text"], user_id: current_user.id)

    if @gossip.save
      flash[:success] = "Ton potin a bien été ajouté"
      redirect_to root_path
    else
      render new_gossip_path
    end 
  end

  def index
    puts "homepage displayed"
    @gossips = Gossip.all 
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comment = Comment.new
  end 

  def edit 
    @gossip = Gossip.find(params[:id])
  end 

  def update
    @gossip = Gossip.find(params[:id])

    if @gossip.update(gossip_params)
      flash[:success] = "Ton potin a bien été modifié"
      redirect_to @gossip
    else
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])

    if @gossip.destroy
      puts "potin supprimé"
      flash[:success] = "Le potin a bien été supprimé"
      redirect_to root_path
    else 
      flash[:danger] = "Le potin n'a pas pu être supprimé"
      puts @gossip.errors
      redirect_to @gossip
    end 
  end 
    

  private 

  def authenticate_user
    unless current_user
      flash[:danger] = "Connecte toi pour pouvoir publier des potins"
      redirect_to new_session_path
    end
  end

  def is_author?
    @gossip = Gossip.find(params[:id])
    unless current_user == @gossip.user
      flash[:danger] = "Tu ne peux pas toucher à ce potin, tu n'es pas l'auteur."
      redirect_to root_path
    end 
  end 

  def gossip_params
    gossip_params = params.permit(:title, :content)
  end

end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/views/gossips/edit.html.erb
<html>
  <body>
    <% if @gossip.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <p>Nous n'avons pas réussi à modifier le potin pour la (ou les) raison(s) suivante(s) :</p>
      <ul>
        <% @gossip.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    
    <div class="container">
        <h1>Modifie ton potin :</h1>

        <%= form_tag url_for(action: 'update'), method: "PATCH" do %>
        <div class="form-group">
          <%= text_field_tag 'title', @gossip.title, class: 'form-control' %>
          <br />
        </div>
        <div class="form-group">
          <%= text_area_tag 'content', @gossip.content, class: 'form-control' %>
          <br />
        </div>
          <%= submit_tag "Valider", class: "btn btn-info" %>
        <% end %>
    </div>

  </body>
</html>

app/views/gossips/index.html.erb
<div class="jumbotron">
    <div class="container">
        <h1 class="diplay-3"> Bienvenue sur mon site de Potins</h1>
        <h3 class="diplay-5"> Prêt à Bitcher ?</h3>
    </div>
</div>

<div class="container">
    <div ><h1>Index</h1>
        <p>Mon site référence les potins, voilà la liste actuelle, du plus récent au plus ancien :</p>
    </div> 
    <div class="list-group">
        <% @gossips.sort {|a,b| b.created_at <=> a.created_at }.each do |gossip| %>
            <a href= <%= gossip_path(gossip.id) %> class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1"><%= gossip.title%></h5>
                    <small><%= gossip.created_at.strftime("%Y-%m-%d %H:%M:%S") %></small>
                </div>
                <p class="mb-1"><%= gossip.content %></p>
                <div class="d-flex w-100 justify-content-between">
                    <small><%= gossip.user.first_name %></small>
                    <span class="badge badge-primary badge-pill"> <%= gossip.comments.size %> </span>
                </div>
            </a> 
        <% end %>
    </div>    
</div>

app/views/gossips/new.html.erb
<html>
  <body>
    <% if @gossip.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
      <ul>
        <% @gossip.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    
    <div class="container">
      <div class=text-center>
        <h1>Balance un nouveau doss !</h1>

        <%= form_tag gossips_path, method: "post" do %>
        <div class="form-group">
          <%= label_tag 'Titre' %><br/>
          <%= text_field_tag 'gossip_title' %>
          <br /> <br />
        </div>
        <div class="form-group">
          <%= label_tag 'Potin' %><br/>
          <%= text_area_tag 'gossip_text' %>
          <br /> <br />
        </div>
          <%= submit_tag "Valider", class: "btn btn-info" %>
        <% end %>
      </div>
    </div>

  </body>
</html>

app/views/gossips/show.html.erb
<br/><br/>
<div class="container">
    <div class="row"> <h5>Potin : </h5> </div>
    <div class="row">
        <div class="card border-secondary col">
            <div class="card-header bg-transparent border-secondary"> <%= @gossip.title %> </div>
            <div class="card-body text-secondary">
                <p class="card-text"><%= @gossip.content %></p>
            </div>
            <div class="card-footer bg-transparent border-secondary">
                créé par <%= link_to @gossip.user.first_name, user_path(@gossip.user.id), class:"text-info" %> 
                <% if @gossip.user.city != nil %>
                    de <%= link_to @gossip.user.city.name, city_path(@gossip.user.city.id), class:"text-info" %>
                <% end %></p>    
            </div>
        </div>
    </div>
    <br/>
    <div class="row">
        <%= link_to "Modifier", edit_gossip_path(@gossip.id), class: "btn btn-light"%> 
        <%= link_to "Supprimer", gossip_path(@gossip.id), data: {method: :delete, confirm: "Es-tu sûr.e de vouloir supprimer ce potin ?"}, class: "btn btn-danger"%> 
    </div><br/>
    <div class="row">
        <ul class="list-group list-group-flush col-10 d-flex justify-content-right">
        <h5>Commentaires : </h5>
            <% @gossip.comments.all.each do |comment| %>
            <li class="list-group-item"> 
                <%= comment.content %> <br/> 
                <small> <%= comment.user.email %> <%= comment.created_at.strftime("%Y-%m-%d %H:%M:%S") %> </small>
            </li>
            <% end %>
            <li class="list-group-item">
                <%= form_for [ @gossip, @comment ] do |f| %>
                    <div class="form-group">
                        <%= f.text_area :content, class: 'form-control'%>
                    </div>
                    <%= f.submit "Envoyer", class: "btn btn-info" %>
                <% end %>

            </li>

        </ul>
    </div>

</div>



        