config/routes.rb
Rails.application.routes.draw do
  resources :teams, only: [:index]
  resources :contacts, only: [:index]
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]
  resources :gossips do
    resources :comments
  end
  root 'gossips#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    validates :name, presence: true
    validates :zip_code, format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" }
    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :gossip
    validates :content, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    validates :title, presence: true, length: { minimum: 3, maximum: 14}
    validates :content, presence: true
    belongs_to :user
    has_many :gossip_tags
    has_many :tags, through: :gossip_tags
    has_many :comments

    def self.count 
        return self.all.size 
    end 

    def self.get_author_first_names
        author_array = []
        self.all.each do |g|
            author_array << g.user.first_name
        end 
        return author_array
    end 

    def self.get_titles
        title_array = []
        self.all.each do |g|
            title_array << g.title 
        end
        return title_array
    end 

end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
    belongs_to :gossip
    belongs_to :tag
end

app/models/message_delivering.rb
class MessageDelivering < ApplicationRecord
    # 1-N association with recipients (users) table
    # class_name tells rails recipient is a user
    belongs_to :recipient, class_name: 'User'

    # 1-N association with received_messages (private_messages) table
    # class_name tells rails received_message is a private_message
    belongs_to :received_message, class_name: 'PrivateMessage'

end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    # 1-N association with senders (users) table
    belongs_to :sender, class_name: 'User'

    # 1-N association with message_deliverings table
    has_many :message_deliverings, foreign_key: :received_message_id

    # N-N association with recipients (users) table via message_deliverings table
    has_many :recipients, through: :message_delivering, source: :recipient
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :title, presence: true, length: { maximum: 100}
    has_many :gossip_tags
    has_many :gossips, through: :gossip_tags 
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    validates :email, presence: true
    belongs_to :city, optional: true
    has_many :gossips
    has_many :comments
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"

    def remember(remember_token)
        remember_digest = BCrypt::Password.create(remember_token)
        self.update(remember_digest: remember_digest)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    puts "see my page team"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(email: params[:email], password: params[:password], city_id: rand(1..10))

    if @user.save
      flash[:success] = "Session créée, bienvenu.e dans la communauté des potins !"
      #création d'une session
      log_in(user)
      #création d'un cookie
      remember(user)
      redirect_to root_path
    else
      puts @user
      puts "user not saved due to errors"
      puts @user.errors.full_messages
      render new_user_path
    end 
  end

  def update
  end

  def show
    @user = User.all.find(params[:id].to_i)
  end

  def destroy
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def current_user
        if session[:user_id]
            User.find_by(id: session[:user_id])
        elsif cookies[:user_id]
            user = User.find_by(id: cookies[:user_id])
            if user
                # nous allons prendre le remember_token stocké en cookie, le hasher, puis le comparer avec notre remember_digest stocké en base
                remember_token = cookies[:remember_token]
                remember_digest = user.remember_digest
                user_authenticated = BCrypt::Password.new(remember_digest).is_password?(remember_token)
                # si tout est bon, il ne nous reste plus qu'à souhaiter bienvenue à l'utilisateur !
                if user_authenticated
                  log_in user
                  current_user = user
                end
            end
        end
    end
    
    def log_in(user)
        session[:user_id] = user.id
    end

    def remember(user)
        # ici je vais créer un remember_token qui est une suite aléatoire de caractères
        remember_token = SecureRandom.urlsafe_base64
      
        # j'ai mon token, je vais stocker son digest en base de données :    
        user.remember(remember_token)
      
        #  maintenant, je vais créer les cookies : un cookie qui va conserver l'user_id, et un autre qui va enregistrer le remember_token
        cookies.permanent[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
      
    end

    def forget(user)
        # on remet le remember_digest à nil puisqu'il ne nous servira plus :
        user.update(remember_digest: nil)
      
        # on efface les cookies dans le navigateur de l'utilisateur
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end

    def log_out(user)
        session.delete(:user_id)
        forget(user)
    end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GossipProjectNew</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="navbar-brand"> <%= link_to "TheGossipProject", root_path, class: "navbar-brand" %></div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to "Nouveau Potin", new_gossip_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Team", teams_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", contacts_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
    
    <% if session[:user_id] == nil %>
      <%= link_to "Se connecter", new_session_path, class: "nav-item btn btn-outline-dark" %>
      <%= link_to "Créer un compte", new_user_path, class: "nav-item btn btn-info"%>
    <% else %>
      <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-info" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.email %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Profil</a>
            <%= link_to "Se déconnecter", session_path(session.id), method: :delete, class: "dropdown-item" %>
          </div>
      </div>
      <% end %>
  </nav>

  <% if flash[:success] != nil %>
    <div class="alert alert-success" role="alert"><%= flash[:success] %></div>
  <% end %>
  <% if flash[:logout] != nil %>
    <div class="alert alert-warning" role="alert"><%= flash[:logout] %></div>
  <% end %>
  <% if flash[:danger] != nil %>
    <div class="alert alert-danger" role="alert"><%= flash[:danger] %></div>
  <% end %>

  <%= yield %>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  
  </body>
</html>

app/views/pages/Contact.html.erb
<div class="container">
    <div class="text-center">
        <h1>Contact</h1>
        <p>Tu peux contacter la team sur slack, les mails c'est has been !</p>
    </div>
</div>

app/views/pages/Team.html.erb
<div class="container">
    <div class="text-center">
        <h1>Team</h1>
        <p>Seul on va plus vite, ensemble on va plus loin</p>
        <p> Chez nous il y a : <br/>
        <p>Jay, the best</p>
        <p>Mack, the hero</p>
        <p>Kim, the creative</p>
        <p>Francky, the funniest</p>
        <p>Lucas, the graphist</p>
        <p>Guillaume, the business man</p>
        <p>... et moi</p>
    </div>
</div>

app/views/pages/gossip.html.erb
<div class="text-center">
    <p> <%= @title %> : </p>
    <H1> <%= @content %> </h1>
    <p> créé par <%= link_to @author, user_path(@user_id) %> le <%= @created_at%>
</div>

app/views/pages/home.html.erb
<div class="text-center">
    <h1>Index</h1>
    <p>Mon site référence les potins, voilà la liste actuelle (il y a <%= @gossips_count %> potins) :</p>
    <div class="row">
    <% @gossips_array.each_with_index do |gossip, i| %>
        <div class="col-sm-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title"><%= @title_array[i] %></h5>
                    <p class="card-text">auteur : <%= @author_array[i] %></p>
                    <%= link_to "Details", gossip_path(i) %> </p><br/>
                </div>
            </div>
        </div>
    <% end %>
    </div>
</div>